# -*- coding: utf-8 -*-
"""Create Metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGNaewPCLIQYapij_MmWbyOX7m6l-A-s

**eliminate duplication of tourist attractions**
"""

import pandas as pd

df = pd.read_excel('cleaned_data_final.xlsx')

def generate_metadata(description, city, category):
    description = description.strip() if isinstance(description, str) else ''
    city = city.strip() if isinstance(city, str) else ''
    category = category.strip() if isinstance(category, str) else ''

    return f"{description} {category} {city}"

df['Metadata'] = df.apply(
    lambda row: generate_metadata(row.get('Description', ''),
                                  row.get('City', ''),
                                  row.get('Category','')),axis=1
)

output_path = 'merge_dataset.xlsx'
df.to_excel(output_path, index=False)

print(f"File saved as {output_path}")