# -*- coding: utf-8 -*-
"""Create Metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGNaewPCLIQYapij_MmWbyOX7m6l-A-s
"""

import pandas as pd

df = pd.read_excel('dataset_jkt.xlsx')

def generate_metadata(overview, category, city):
    overview = overview.strip() if isinstance(overview, str) else ''
    category = category.strip().lower() if isinstance(category, str) else ''
    city = city.strip() if isinstance(city, str) else ''

    return f"{overview} {category} {city}"

df['Metadata'] = df.apply(
    lambda row: generate_metadata(row.get('Overview', ''), row.get('Category', ''), row.get('City', '')),
    axis=1
)

output_path = 'updated_dataset_jkt.xlsx'
df.to_excel(output_path, index=False)

print(f"File saved as {output_path}")